#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libblockdev
Version  : 2.15.1
Release  : 2
URL      : https://github.com/storaged-project/libblockdev/archive/2.15-1.tar.gz
Source0  : https://github.com/storaged-project/libblockdev/archive/2.15-1.tar.gz
Summary  : A library with utility functions used by the libblockdev library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libblockdev-legacypython
Requires: libblockdev-python3
Requires: libblockdev-lib
Requires: libblockdev-python
BuildRequires : nss-dev
BuildRequires : pkgconfig(bytesize)
BuildRequires : pkgconfig(devmapper)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(libcryptsetup)
BuildRequires : pkgconfig(libkmod)
BuildRequires : pkgconfig(libparted)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(mount)
BuildRequires : python-dev
BuildRequires : volume_key-dev

%description
### CI status
<img alt="CI status" src="https://fedorapeople.org/groups/storage_apis/statuses/libblockdev-master.svg" width="100%" height="300ex" />

%package dev
Summary: dev components for the libblockdev package.
Group: Development
Requires: libblockdev-lib
Provides: libblockdev-devel

%description dev
dev components for the libblockdev package.


%package legacypython
Summary: legacypython components for the libblockdev package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the libblockdev package.


%package lib
Summary: lib components for the libblockdev package.
Group: Libraries

%description lib
lib components for the libblockdev package.


%package python
Summary: python components for the libblockdev package.
Group: Default
Requires: libblockdev-legacypython
Requires: libblockdev-python3

%description python
python components for the libblockdev package.


%package python3
Summary: python3 components for the libblockdev package.
Group: Default
Requires: python3-core

%description python3
python3 components for the libblockdev package.


%prep
%setup -q -n libblockdev-2.15-1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1513191457
%autogen --disable-static --with-dm=no
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1513191457
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/blockdev/blockdev.h
/usr/include/blockdev/btrfs.h
/usr/include/blockdev/crypto.h
/usr/include/blockdev/dev_utils.h
/usr/include/blockdev/exec.h
/usr/include/blockdev/extra_arg.h
/usr/include/blockdev/fs.h
/usr/include/blockdev/fs/ext.h
/usr/include/blockdev/fs/generic.h
/usr/include/blockdev/fs/mount.h
/usr/include/blockdev/fs/ntfs.h
/usr/include/blockdev/fs/vfat.h
/usr/include/blockdev/fs/xfs.h
/usr/include/blockdev/kbd.h
/usr/include/blockdev/loop.h
/usr/include/blockdev/lvm.h
/usr/include/blockdev/mdraid.h
/usr/include/blockdev/module.h
/usr/include/blockdev/mpath.h
/usr/include/blockdev/part.h
/usr/include/blockdev/plugins.h
/usr/include/blockdev/sizes.h
/usr/include/blockdev/swap.h
/usr/include/blockdev/utils.h
/usr/lib64/libbd_btrfs.so
/usr/lib64/libbd_crypto.so
/usr/lib64/libbd_fs.so
/usr/lib64/libbd_kbd.so
/usr/lib64/libbd_loop.so
/usr/lib64/libbd_lvm-dbus.so
/usr/lib64/libbd_lvm.so
/usr/lib64/libbd_mdraid.so
/usr/lib64/libbd_mpath.so
/usr/lib64/libbd_part.so
/usr/lib64/libbd_part_err.so
/usr/lib64/libbd_swap.so
/usr/lib64/libbd_utils.so
/usr/lib64/libblockdev.so
/usr/lib64/pkgconfig/blockdev-utils.pc
/usr/lib64/pkgconfig/blockdev.pc

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libbd_btrfs.so.2
/usr/lib64/libbd_btrfs.so.2.0.0
/usr/lib64/libbd_crypto.so.2
/usr/lib64/libbd_crypto.so.2.0.0
/usr/lib64/libbd_fs.so.2
/usr/lib64/libbd_fs.so.2.0.0
/usr/lib64/libbd_kbd.so.2
/usr/lib64/libbd_kbd.so.2.0.0
/usr/lib64/libbd_loop.so.2
/usr/lib64/libbd_loop.so.2.0.0
/usr/lib64/libbd_lvm-dbus.so.2
/usr/lib64/libbd_lvm-dbus.so.2.0.0
/usr/lib64/libbd_lvm.so.2
/usr/lib64/libbd_lvm.so.2.0.0
/usr/lib64/libbd_mdraid.so.2
/usr/lib64/libbd_mdraid.so.2.0.0
/usr/lib64/libbd_mpath.so.2
/usr/lib64/libbd_mpath.so.2.0.0
/usr/lib64/libbd_part.so.2
/usr/lib64/libbd_part.so.2.0.0
/usr/lib64/libbd_part_err.so.2
/usr/lib64/libbd_part_err.so.2.0.0
/usr/lib64/libbd_swap.so.2
/usr/lib64/libbd_swap.so.2.0.0
/usr/lib64/libbd_utils.so.2
/usr/lib64/libbd_utils.so.2.1.0
/usr/lib64/libblockdev.so.2
/usr/lib64/libblockdev.so.2.0.0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
